import { NgModule } from '@angular/core';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {MatButtonModule, MatCheckboxModule, MatListModule, MatToolbarModule, MatSidenavModule, MatIconModule,
        MatCardModule, MatMenuModule, MatInputModule, MatAutocompleteModule, MatButtonToggleModule, MatDatepickerModule,
        MatTabsModule, MatRadioModule, MatDialogModule, MatSelectModule, MatSliderModule, MatTooltipModule, MatGridListModule,
        MatStepperModule, MatSnackBarModule, MatExpansionModule, MatFormFieldModule, MatPaginatorModule, MatProgressBarModule,
        MatSortModule, MatLineModule, MatChipsModule, MatTableModule, MatSlideToggleModule} from '@angular/material';


@NgModule({
  imports: [
    BrowserAnimationsModule,
    MatButtonModule,
    MatCheckboxModule,
    MatListModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatMenuModule,
    MatInputModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatDatepickerModule,
    MatTabsModule,
    MatRadioModule,
    MatDialogModule,
    MatSelectModule,
    MatSliderModule,
    MatTooltipModule,
    MatGridListModule,
    MatStepperModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatSortModule,
    MatLineModule,
    MatChipsModule,
    MatTableModule,
    MatSlideToggleModule
  ],
  exports: [
    BrowserAnimationsModule,
    MatButtonModule,
    MatCheckboxModule,
    MatListModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatCardModule,
    MatMenuModule,
    MatInputModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatDatepickerModule,
    MatTabsModule,
    MatRadioModule,
    MatDialogModule,
    MatSelectModule,
    MatSliderModule,
    MatTooltipModule,
    MatGridListModule,
    MatStepperModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatSortModule,
    MatLineModule,
    MatChipsModule,
    MatTableModule,
    MatSlideToggleModule
  ],
  declarations: []
})
export class MaterialModule { }
